export const GET_ALL_QUESTIONS_ANSWERS = 'GET_ALL_QUESTIONS_ANSWERS';
export const SET_QUESTIONS_ANSWERS = 'SET_QUESTIONS_ANSWERS';
export const SET_QUESTIONS_ANSWERS_LOADING = 'SET_QUESTIONS_ANSWERS_LOADING';
export const SET_QUESTIONS_ANSWERS_ERROR = 'SET_QUESTIONS_ANSWERS_ERROR';
export const ADD_QUESTIONS_ANSWERS = 'ADD_QUESTIONS_ANSWERS';
export const DELETE_QUESTIONS_ANSWERS = 'DELETE_QUESTIONS_ANSWERS';
export const SET_CURRENT_QUESTIONS_ANSWERS = 'SET_CURRENT_QUESTIONS_ANSWERS';
export const GET_QUESTIONS_ANSWERS_BY_ID = 'GET_QUESTIONS_ANSWERS_BY_ID';
export const UPDATE_QUESTIONS_ANSWERS = 'UPDATE_QUESTIONS_ANSWERS';
export const REMOVE_QUESTIONS_ANSWERS_FROM_STORE =
  'REMOVE_QUESTIONS_ANSWERS_FROM_STORE';
