export const GET_ALL_EMAIL_QUESTIONS = 'GET_ALL_EMAIL_QUESTIONS';
export const SET_ALL_EMAIL_QUESTIONS = 'SET_ALL_EMAIL_QUESTIONS';
export const GET_EMAIL_QUESTION_BY_ID = 'GET_EMAIL_QUESTION_BY_ID';
export const SET_CURRENT_EMAIL_QUESTION = 'SET_CURRENT_EMAIL_QUESTION';
export const MOVE_EMAIL_QUESTIONS_TO_SPAM = 'MOVE_EMAIL_QUESTIONS_TO_SPAM';
export const ANSWER_TO_EMAIL_QUESTION = 'ANSWER_TO_EMAIL_QUESTION';
export const DELETE_EMAIL_QUESTIONS = 'DELETE_EMAIL_QUESTIONS';
export const SET_EMAIL_QUESTIONS_LOADING = 'SET_EMAIL_QUESTIONS_LOADING';
export const SET_EMAIL_QUESTIONS_ERROR = 'SET_EMAIL_QUESTIONS_ERROR';
export const SET_EMAIL_QUESTIONS_PAGES_COUNT =
  'SET_EMAIL_QUESTIONS_PAGES_COUNT';
export const SET_EMAIL_QUESTION_CURRENT_PAGE =
  'SET_EMAIL_QUESTION_CURRENT_PAGE';
export const SET_EMAIL_QUESTIONS_PENDING_COUNT =
  'SET_EMAIL_QUESTIONS_PENDING_COUNT';
export const GET_EMAIL_QUESTIONS_PENDING_COUNT =
  'GET_EMAIL_QUESTIONS_PENDING_COUNT';
