export const GET_CERTIFICATES_LIST = 'GET_CERTIFICATES_LIST';
export const SET_CERTIFICATES_LIST = 'SET_CERTIFICATES_LIST';
export const DELETE_CERTIFICATE = 'DELETE_CERTIFICATE';
export const REMOVE_CERTIFICATE_FROM_STORE = 'REMOVE_CERTIFICATE_FROM_STORE';
