export const GET_ALL_BUSINESS_PAGES = 'GET_ALL_BUSINESS_PAGES';
export const SET_BUSINESS_PAGES = 'SET_BUSINESS_PAGES';
export const SET_LOADING = 'SET_LOADING';
export const SET_BUSINESS_PAGES_ERROR = 'SET_BUSINESS_PAGES_ERROR';
