const buttonTitles = {
  DELETE_TITLE: 'Видалити',
  EDIT_TITLE: 'Редагувати',
  CREATE_NEWS_TITLE: 'Додати новину',
  CREATE_PATTERN_TITLE: 'Додати гобелен',
  CREATE_MODEL_TITLE: 'Додати модель',
  MODEL_SAVE_TITLE: 'Зберегти',
  MODEL_CONSTRUCTOR: 'Конструктор',
  CANCEL_TITLE: 'Ні',
  LOGOUT_TITLE: 'Вихід',
  CREATE_BUSINESS_PAGE: 'Додати бізнес сторінку',
  CREATE_CONTACT_TITLE: 'Додати контакти',
  SWITCH_USER_STATUS_TITLE: 'Змінити статус користувача',
  USER_INACTIVE_TITLE: 'Деактивувати',
  USER_ACTIVE_TITLE: 'Активувати',
  ADD_CATEGORY: 'Додати категорію',
  GO_BACK_TITLE: 'Назад',
  ADD_CATEGORY_IMAGE: 'Додати зображення',
  ADD_CATEGORY_NAME: 'Додати назву',
  CANCEL: 'Відмінити',
  SAVE_CATEGORY: 'Зберегти категорію',
  CREATE_SPECIAL_USER: 'Створити спецкористувача',
  ADD_PHOTO_LABEL: '+',
  CREATE_CATEGORY: 'Створити категорію',
  PATTERN_REMOVE_MESSAGE: 'Ви впевнені, що хочете видалити цей гобелен?',
  REMOVE_CONTACT_MESSAGE: 'Ви впевнені, що хочете видалити цей контакт?',
  USER_UNACTIVE_TITLE: 'Деактивувати',
  SHOW_COMMENTS_TITLE: 'Переглянути коментарі',
  HIDE_COMMENTS_TITLE: 'Приховати коментарі',
  SAVE_ORDER: 'Зберегти замовлення',
  SAVE_TITLE: 'Зберегти',
  UNDERSTAND: 'Зрозуміло',
  ANSWER: 'Відповісти',
  TO_SPAM: 'У СПАМ',
  MOVE_ALL_TO_SPAM: 'Перемістити у СПАМ',
  CREATE_SIZE_TITLE: 'Створити розмір',
  SAVE_SIZE_TITLE: 'Зберегти розмір',
  CREATE_MATERIAL_TITLE: 'Створити матеріал',
  CREATE_COLOR_TITLE: 'Створити колір',
  UPDATE_COLOR_TITLE: 'Зберегти зміни',
  SAVE_MATERIAL: 'Зберегти матеріал',
  CREATE_HEADER_TITLE: 'Створити посилання',
  HEADER_SAVE_TITLE: 'Зберегти посилання',
  GO_TO_MATERIAL_COLOR_PALLET: 'Редагувати палітру',
  CLOSE_DIALOG_TITLE: 'Закрити вікно',
  ORDER_DETAILS: 'Деталі',
  USER_STATUS_TITLE: 'Статус',
  CLEAR_FILTERS: 'Очистити фільтри',
  CREATE_SLIDE_TITLE: 'Створити слайд',
  OPEN_SLIDE_EDIT: 'Увімкнути редагування',
  SAVE_SLIDE_ORDER: 'Зберегти зміни',
  CANCEL_SLIDE_ORDER: 'Скасувати зміни',
  AUTHOR_PHOTO: 'Фото Автора',
  MAIN_PHOTO: 'Головне Фото',
  CREATE_CONSTRUCTOR_BASIC_TITLE: 'Додати основу',
  CREATE_CONSTRUCTOR_FRONT_POCKET_TITLE: 'Додати передню кишеню',
  CREATE_CONSTRUCTOR_BOTTOM_TITLE: 'Додати низ',
  GO: 'Перейти',
  CATEGORY_TITLE: 'Категорія',
  LOOK: 'Переглянути',
  ADD_ORDER: 'Додати замовлення',
  USER_ROLE_TITLE: 'Роль',
  EVENT_TITLE: 'Подія',
  SEND_CONFIRM: 'Надіслати підтвердження',
  SEND_CODE: 'Надіслати код для підтвердження',
  EXIT_WITHOUT_SAVING: 'Вийти без збереження',
  ORDER_STATUS: 'Статус замовлення',
  PAYMENT_STATUS: 'Статус оплати',
  SIZE_NAME: 'Розмір',
  AVAILABLE: 'Доступність',
  PURPOSE: 'Застосування',
  CATEGORY: 'Категорії',
  PATTERN: 'Гобелени',
  MODEL: 'Моделі',
  YES_BUTTON: 'Так',
  NO_BUTTON: 'Ні',
  PATTERN_AVAILABLE: 'Доступний'
};

export default buttonTitles;
