const routes = {
  pathToLogin: '/',
  pathToPatterns: '/patterns',
  pathToPatternDetails: '/patterns/:id',
  pathToAddPattern: '/patterns/add',
  pathToNews: '/news',
  pathToNewsDetails: '/news/:id',
  pathToAddNews: '/newsadd',
  pathToBusinessPages: '/business-pages',
  pathToAddBusinessPage: '/business-page-add',
  pathToBusinessPageDetails: '/business-pages/:id',
  pathToUsers: '/users',
  pathToUsersDetails: '/users/:id',
  pathToProducts: '/products',
  pathToCategories: '/categories',
  pathToAddCategory: '/add-category',
  pathToEditCategory: '/add-category/:id',
  pathToRegisterAdmin: '/register',
  pathToConfirmAdmin: '/confirmation/:token',
  pathToContacts: '/contacts',
  pathToContactsEdit: '/contacts/:id',
  pathToAddContact: '/add-contact',
  pathToComments: '/comments',
  pathToHomePageEdit: '/home-page-edit'
};
export default routes;
