const routes = {
  pathToLogin: '/',
  pathToPatterns: '/patterns',
  pathToPatternDetails: '/patterns/:id',
  pathToAddPattern: '/patterns/add',
  pathToNews: '/news',
  pathToNewsDetails: '/news/:id',
  pathToAddNews: '/newsadd',
  pathToBusinessPages: '/business-pages',
  pathToAddBusinessPage: '/business-page-add',
  pathToBusinessPageDetails: '/business-pages/:id',
  pathToUsers: '/users',
  pathToUsersDetails: '/users/:id',
  pathToProducts: '/products',
  pathToAddProduct: '/add-product',
  pathToEditProduct: '/product/:id',
  pathToCategories: '/categories',
  pathToAddCategory: '/add-category',
  pathToEditCategory: '/add-category/:id',
  pathToRegisterAdmin: '/register',
  pathToConfirmAdmin: '/confirmation/:token',
  pathToContacts: '/contacts',
  pathToContactsEdit: '/contacts/:id',
  pathToAddContact: '/add-contact',
  pathToOrders: '/orders',
  pathToComments: '/comments',
  pathToEmailQuestions: '/email-questions',
  pathToEmailQuestionDetails: '/email-answer/:id',
  pathToMaterials: '/materials',
  pathToAddMaterial: '/material/add',
  pathToMaterialDetails: '/materials/:id',
  pathToStatistic: '/stats',
  pathToModels: '/models',
  pathToModelDetails: '/models/:id',
  pathToAddModel: '/models/add'
};
export default routes;
