export const ADD_CONSTRUCTOR_BASIC = 'ADD_CONSTRUCTOR_BASIC';
export const DELETE_CONSTRUCTOR_BASIC = 'DELETE_CONSTRUCTOR_BASIC';
export const DELETE_CONSTRUCTOR = 'DELETE_CONSTRUCTOR';
export const UPDATE_CONSTRUCTOR_BASIC = 'UPDATE_CONSTRUCTOR_BASIC';
export const ADD_CONSTRUCTOR_FRONT_POCKET = 'ADD_CONSTRUCTOR_FRONT_POCKET';
export const GET_CONSTRUCTORS = 'GET_CONSTRUCTORS';
export const GET_CONSTRUCTOR = 'GET_CONSTRUCTOR';
export const UPDATE_CONSTRUCTOR = 'UPDATE_CONSTRUCTOR';
export const ADD_CONSTRUCTOR = 'ADD_CONSTRUCTOR';
export const SET_CONSTRUCTORS = 'SET_CONSTRUCTORS';
export const SET_CONSTRUCTOR = 'SET_CONSTRUCTOR';
export const SET_CONSTRUCTOR_LOADING = 'SET_CONSTRUCTOR_LOADING';
export const SET_CONSTRUCTOR_ERROR = 'SET_CONSTRUCTOR_ERROR';
export const REMOVE_CONSTRUCTOR_FROM_STORE = 'REMOVE_CONSTRUCTOR_FROM_STORE';
export const DELETE_CONSTRUCTOR_FRONT_POCKET =
  'DELETE_CONSTRUCTOR_FRONT_POCKET';
export const UPDATE_CONSTRUCTOR_FRONT_POCKET =
  'UPDATE_CONSTRUCTOR_FRONT_POCKET';
export const ADD_CONSTRUCTOR_BOTTOM = 'ADD_CONSTRUCTOR_BOTTOM';
export const DELETE_CONSTRUCTOR_BOTTOM = 'DELETE_CONSTRUCTOR_BOTTOM';
export const UPDATE_CONSTRUCTOR_BOTTOM = 'UPDATE_CONSTRUCTOR_BOTTOM';
export const ADD_CONSTRUCTOR_PATTERN = 'ADD_CONSTRUCTOR_PATTERN';
export const DELETE_CONSTRUCTOR_PATTERN = 'DELETE_CONSTRUCTOR_PATTERN';
export const SET_CONSTRUCTOR_ELEMENT_METHOD = 'SET_CONSTRUCTOR_ELEMENT_METHOD';
export const SET_EDITABLE_CONSTRUCTOR_ELEMENT =
  'SET_EDITABLE_CONSTRUCTOR_ELEMENT';
export const SET_CONSTRUCTOR_TABS = 'SET_CONSTRUCTOR_TABS';
