export const GET_COMMENTS_BY_TYPE = 'GET_COMMENTS_BY_TYPE';
export const GET_USER_COMMENTS = 'GET_USER_COMMENTS';
export const GET_PRODUCT_COMMENTS = 'GET_PRODUCT_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_LOCALLY = 'DELETE_COMMENT_LOCALLY';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
export const SET_COMMENTS_ERROR = 'SET_COMMENTS_ERROR';
