export const SET_MODELS = 'SET_MODELS';
export const GET_MODELS = 'GET_MODELS';
export const DELETE_MODEL = 'DELETE_MODEL';
export const ADD_MODEL = 'ADD_MODEL';
export const GET_MODEL = 'GET_MODEL';
export const SET_MODEL = 'SET_MODEL';
export const SET_MODEL_LOADING = 'SET_MODEL_LOADING';
export const UPDATE_MODEL = 'UPDATE_MODEL';
export const SET_MODEL_ERROR = 'SET_MODEL_ERROR';
export const REMOVE_MODEL_FROM_STORE = 'REMOVE_MODEL_FROM_STORE';
export const ADD_CONSTRUCTOR_BASIC_TO_STORE = 'ADD_CONSTRUCTOR_BASIC_TO_STORE';
export const EDIT_CONSTRUCTOR_BASIC_IN_STORE =
  'EDIT_CONSTRUCTOR_BASIC_IN_STORE';
export const REMOVE_CONSTRUCTOR_BASIC_FROM_STORE =
  'REMOVE_CONSTRUCTOR_BASIC_FROM_STORE';
export const ADD_CONSTRUCTOR_BOTTOM_TO_STORE =
  'ADD_CONSTRUCTOR_BOTTOM_TO_STORE';
export const REMOVE_CONSTRUCTOR_BOTTOM_FROM_STORE =
  'REMOVE_CONSTRUCTOR_BOTTOM_FROM_STORE';
export const EDIT_CONSTRUCTOR_BOTTOM_IN_STORE =
  'EDIT_CONSTRUCTOR_BOTTOM_IN_STORE';
export const ADD_CONSTRUCTOR_POCKET_TO_STORE =
  'ADD_CONSTRUCTOR_POCKET_TO_STORE';
export const REMOVE_CONSTRUCTOR_POCKET_FROM_STORE =
  'REMOVE_CONSTRUCTOR_POCKET_FROM_STORE';
export const EDIT_CONSTRUCTOR_POCKET_IN_STORE =
  'EDIT_CONSTRUCTOR_POCKET_IN_STORE';
export const ADD_CONSTRUCTOR_PATTERN_TO_STORE =
  'ADD_CONSTRUCTOR_PATTERN_TO_STORE';
export const REMOVE_CONSTRUCTOR_PATTERN_FROM_STORE =
  'REMOVE_CONSTRUCTOR_PATTERN_FROM_STORE';
