export const SET_DIALOG_STATUS = 'SET_DIALOG_STATUS';
export const SET_DIALOG_TITLE = 'SET_DIALOG_TITLE';
export const SET_DIALOG_CONTENT = 'SET_DIALOG_CONTENT';
export const SET_BUTTON_TITLE = 'SET_BUTTON_TITLE';
export const SET_ON_CLICK_HANDLER = 'SET_ON_CLICK_HANDLER';
