export const SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGES_COUNT = 'SET_PAGES_COUNT';
export const SET_TABLE_DENSE = 'SET_TABLE_DENSE';
export const SET_ITEMS_COUNT = 'SET_ITEMS_COUNT';
export const RESET_PAGINATION = 'RESET_PAGINATION';
