export const SET_HOME_PAGE_DATA = 'SET_HOME_PAGE_DATA';
export const GET_HOME_PAGE_DATA = 'GET_HOME_PAGE_DATA';
export const SET_HOME_PAGE_DATA_LOADING = 'SET_HOME_PAGE_DATA_LOADING';
export const UPDATE_HOME_PAGE_DATA_IN_STORE = 'UPDATE_HOME_PAGE_DATA_IN_STORE';
export const SET_HOME_PAGE_DATA_ERROR = 'SET_HOME_PAGE_DATA_ERROR';