const SET_POPULAR_CATEGORIES = 'SET_POPULAR_CATEGORIES';
const SET_STATS_LOADING = 'SET_STATS_LOADING';
const SET_DOUGHNUT_VALUE = 'SET_DOUGHNUT_VALUE';
const SET_DATE_VALUE = 'SET_DATE_VALUE';
const SET_BAR_VALUE = 'SET_BAR_VALUE';
const SET_POPULAR_PRODUCTS = 'SET_POPULAR_PRODUCTS';
const GET_INITIAL_STATS = 'GET_INITIAL_STATS';

export {
  SET_POPULAR_CATEGORIES,
  SET_STATS_LOADING,
  SET_DOUGHNUT_VALUE,
  SET_DATE_VALUE,
  SET_BAR_VALUE,
  SET_POPULAR_PRODUCTS,
  GET_INITIAL_STATS
};
