const SET_POPULAR_CATEGORIES = 'SET_POPULAR_CATEGORIES';
const SET_STATS_LOADING = 'SET_STATS_LOADING';
const SET_DOUGHNUT_VALUE = 'SET_DOUGHNUT_VALUE';
const SET_DATE_VALUE = 'SET_DATE_VALUE';
const SET_BAR_VALUE = 'SET_BAR_VALUE';
const SET_POPULAR_PRODUCTS = 'SET_POPULAR_PRODUCTS';
const GET_INITIAL_STATS = 'GET_INITIAL_STATS';
const SET_USERS_STATS = 'SET_USERS_STATS';
const GET_USERS_STATS = 'GET_USERS_STATS';
const GET_ALL_ORDERS_STATS = 'GET_ALL_ORDERS_STATS';
const SET_ALL_ORDERS_STATS = 'SET_ALL_ORDERS_STATS';
const GET_PAID_ORDERS_STATS = 'GET_PAID_ORDERS_STATS';
const SET_PAID_ORDERS_STATS = 'SET_PAID_ORDERS_STATS';
const SET_UPDATING_BAR_DATA = 'SET_UPDATING_BAR_DATA';
const SET_UPDATING_DOGHNUT_DATA = 'SET_UPDATING_DOGHNUT_DATA';

export {
  SET_POPULAR_CATEGORIES,
  SET_STATS_LOADING,
  SET_DOUGHNUT_VALUE,
  SET_DATE_VALUE,
  SET_BAR_VALUE,
  SET_POPULAR_PRODUCTS,
  GET_INITIAL_STATS,
  SET_USERS_STATS,
  GET_ALL_ORDERS_STATS,
  SET_ALL_ORDERS_STATS,
  GET_PAID_ORDERS_STATS,
  SET_PAID_ORDERS_STATS,
  SET_UPDATING_BAR_DATA,
  SET_UPDATING_DOGHNUT_DATA,
  GET_USERS_STATS
};
