const GET_POPULAR_CATEGORIES = 'GET_POPULAR_CATEGORIE';
const SET_POPULAR_CATEGORIES = 'SET_POPULAR_CATEGORIES';
const SET_STATS_LOADING = 'SET_STATS_LOADING';
const SET_DOUGHNUT_VALUE = 'SET_DOUGHNUT_VALUE';
const SET_DATE_VALUE = 'SET_DATE_VALUE';
const SET_BAR_VALUE = 'SET_BAR_VALUE';

export {
  GET_POPULAR_CATEGORIES,
  SET_POPULAR_CATEGORIES,
  SET_STATS_LOADING,
  SET_DOUGHNUT_VALUE,
  SET_DATE_VALUE,
  SET_BAR_VALUE
};
