export const SET_SNACKBAR_SEVERITY = 'SET_SNACKBAR_SEVERITY';
export const SET_SNACKBAR_STATUS = 'SET_SNACKBAR_STATUS';
export const SET_SNACKBAR_MESSAGE = 'SET_SNACKBAR_MESSAGE';
export const SHOW_SUCCESS_SNACKBAR = 'SHOW_SUCCESS_SNACKBAR';
export const SHOW_ERROR_SNACKBAR = 'SHOW_ERROR_SNACKBAR';
